language: go

go:
- 1.11.x

os:
- linux

dist: trusty
sudo: false

before_install:
# Setup dependency management tool
- go get -u -v github.com/golang/dep/cmd/dep
- go get -u github.com/golang/lint/golint
- go get -u golang.org/x/tools/cmd/goimports
- dep ensure

#env:
#  global:
#    - GO111MODULE=on

script:
  - ./ci/travis.gofmt.sh
  - ./ci/travis.govet.sh
  - ./ci/travis.codecov.sh
  - make all

after_success:
  - bash <(curl -s https://codecov.io/bash)
