language: go

go:
  - 1.11.x

os:
  - linux

dist: trusty

sudo: false

before_install:
# Setup dependency management tool
# - go get -u -v github.com/golang/dep/cmd/dep
# - dep ensure
- go get -u golang.org/x/tools/cmd/goimports

env:
 global:
   - GO111MODULE=on

script:
  - ./ci/travis.gofmt.sh
  - ./ci/travis.govet.sh
  - ./ci/travis.codecov.sh
  - make clean all

after_success:
  - bash <(curl -s https://codecov.io/bash)

#before_deploy:
#- make clean all -j2

deploy:
  provider: releases
  api_key:
    secure: AZD7hTgdUSTIQSpK4W+FglXMYbwA8O6ms6CBbh/Dk58RasdCcNciz2LFl7RPZ/fQ4cf+fImA6Fe1/UGCcH6Va2bqUFiYdoh1ef8ba2ou4J1PXHBmZxDmAkcxVqn5T2eakj551FITBxPgfcUEmPIikIPX/QKU/wCbNu62VZ13K7t0LaIFVoe/acBuJ2kYPSz9fKhViWz0QdgFFqmdxJ2znqFBUEUPJ7unQ4RGgK9s9C9o2H9rz3P1aIk2IPzXwj29iQmzQ3UkEj3uF6jJB344bqQY5lYbKG4MlTZDJAQuTdmAVJKl47283bGD/MaB10+12txKHoBXUb/rOreK1Ice3OeMwhyjS0r9Q29noLlMWlISYhNYnlSbqSiIaGfwb8DUg/mY+ZalB2MsfcWbXEqUDuXgqouG+pokT3bGqUUCMcQezobLGiRksyDqKO3eeoRnS2BTpvlUiqa1qZ94rEw8YA2gjscSfXSp7w1/q6NGqxa5iGvbr8zirHP5iiCuQbTLL1vOjtc9/kSjB0CQdXWcEwrAB+gwO5C/gr2ANwio4IEWNyWW0Fcdo89cF5X0tdcwVv/ncBF9rCk18bpT5RhfOcEmstf2GxrigiX+U3+FtTnnlmpY0fiLO7I0eoviIKPF7qkgt8CyKe23l3vLOKtogMlevlVaqK30Awd9z2VEU+8=
  file: build/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true


notifications:
  email: false
