language: go

go:
  - 1.11.x

os:
  - linux

dist: trusty

sudo: false

before_install:
# Setup dependency management tool
# - go get -u -v github.com/golang/dep/cmd/dep
# - dep ensure
- go get -u golang.org/x/tools/cmd/goimports

env:
 global:
   - GO111MODULE=on

script:
  - ./ci/travis.gofmt.sh
  - ./ci/travis.govet.sh
  - ./ci/travis.codecov.sh
  - make clean all

after_success:
  - bash <(curl -s https://codecov.io/bash)

#before_deploy:
#- make clean all -j2

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: build/*
  file_glob: true
  skip_cleanup: true
  draft: true
  on:
    tags: true


notifications:
  email: false
