language: go

go:
- 1.11.x

os:
- linux
- osx

dist: trusty
sudo: false

before_install:
# Setup dependency management tool
- go get -u -v github.com/golang/dep/cmd/dep
- dep ensure

#install:
#  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=master bash)"

#env:
#  global:
#    - GO111MODULE=on

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
